### ISSUE TITLE
Handle timeout error in Verifiable

### ISSUE THREAD

**Issue by shouya** [GeekPark/gpk_account#179]
A `Net::OpenTimeout` occurred in `register#send_verify_code`:

```
execution expired 
app/controllers/concerns/verifiable.rb:23:in `send_to_email' 

------------------------------- 
Session: 
------------------------------- 

* session id: nil 
* data: {} 


------------------------------- 
Backtrace: 
------------------------------- 

app/controllers/concerns/verifiable.rb:23:in `send_to_email' 
app/controllers/concerns/verifiable.rb:7:in `call' 
app/controllers/concerns/verifiable.rb:7:in `send_verify_code' 
```

**Comment by shouya** [comment]
A Net::ReadTimeout occurred in verify_codes#create: 

Net::ReadTimeout 
app/models/verify_code.rb:24:in `send_to_email'

**Comment by shouya** [comment]
https://stackoverflow.com/questions/16040158/rails-mailer-netopentimeout-execution-expired-exception-on-production-serve
